### ISSUE TITLE
Propuesta Diseño

### ISSUE THREAD

**Issue by joelibaceta** [peruanosdev/speakers.peruanos.dev#6]
Pense por lo simple que es la iniciativa mantener un diseño simple de consulta, que pueda alimentarse de una lista de archivos Markdown que cumplan cierto formato, o quizas un archivo yaml, json, etc. 

Siguiendo el formato de archivos "post" de GitHub Pages + Jekyll podríamos automatizar la generacion de un Frontend simple.

![BlackSpeakers](https://user-images.githubusercontent.com/864790/68035161-15572180-fc91-11e9-9c9f-4bf97d9c7d8b.png)

![Propuesta de Diseno1](https://user-images.githubusercontent.com/864790/67983152-1ab15f00-fbf2-11e9-9f01-85c7f70c2e41.png)

**Comment by joelibaceta** [comment]
@darksy12

**Comment by 07Gond** [comment]
Me gusta la idea.

**Comment by darksy12** [comment]
@joelibaceta publico la v1, feedback es bienvenido

https://speakers.peruanos.dev/
