### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by joelibaceta** [peruanosdev/speakers.peruanos.dev#63]
Agregar un Sidebar con informacion sobre el proyecto un link de colaboración y las indicaciones de como sumarse a la lista.

**Comment by darksy12** [comment]
Creo que en este caso si podria ser otra pagina adicional en vez de un sidebar

**Comment by joelibaceta** [comment]
En lo personal, creo que mientras menos navegación mejor :) el Sidebar solo lo tendría en modo web, quizas puedo poner un boceto de que imagino mas tarde para challengear la idea.

**Comment by joelibaceta** [comment]
@hacksy algo así ... 

![Demo](https://user-images.githubusercontent.com/864790/68985105-17b59180-07e2-11ea-814d-104a83084197.png)

**Comment by darksy12** [comment]
Se ve genial!
