### ISSUE TITLE
Añadir separación de topics

### ISSUE THREAD

**Issue by joelibaceta** [peruanosdev/speakers.peruanos.dev#67]
Los topics pueden ser spliteados usando el filtro split de Liquid para permitir mostrarlos como tags separados y uno un stirng único ( _En el futuro útil para búsqueda_ )

**Comment by darksy12** [comment]
Adicionalmente se podria usar un rounded box para mostrarlo ( y mostrarlos como clickeables)

**Comment by joelibaceta** [comment]
@darksy12 como un tag de bootstrap ?
<img width="529" alt="Captura de Pantalla 2019-11-19 a la(s) 11 26 02" src="https://user-images.githubusercontent.com/864790/69165323-66ec1280-0abf-11ea-999c-84685f4781ca.png">
